[tox]
envlist = py313
skipsdist = true
setenv =
    PIP_EXTRA_INDEX_URL = https://pypi.tuna.tsinghua.edu.cn/simple

[travis]
python =
    3.13: py313


[testenv:docs]
basepython = python
changedir = docs
deps = sphinx
commands =
    sphinx-build -b html -d {envtmpdir}/doctrees . {envtmpdir}/html

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    .[legacy]
    pytest~=9.0.3
    pytest-cov~=7.1.0
    freezegun~=1.5.5
    pytest-datadir~=1.8.0
commands =
    python -m pytest
